DROP TABLE IF EXISTS games CASCADE;
CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) NOT NULL,
  opponent_id INTEGER REFERENCES users(id),
  turn INTEGER NOT NULL DEFAULT 1,
  deck_id INTEGER REFERENCES decks(id),
  active BOOLEAN NOT NULL DEFAULT TRUE 
);
